import java.io.File;
import java.io.IOException;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;

public class Selenium_project {
	public static void main(String args[]) throws InterruptedException,IOException 
	{
System.setProperty("webdriver.chrome.driver","C:\\Users\\DELL\\eclipse-workspace\\Selenium\\chrome1\\chromedriver.exe");
WebDriver driver=new ChromeDriver();
//driver.get("https://adactinhotelapp.com/");
//WebElement user = driver.findElement(By.id("username"));
//user.sendKeys("priyavenkataraman");
//WebElement pwd = driver.findElement(By.id("password"));
//pwd.sendKeys("Prajen@09");
//WebElement login = driver.findElement(By.id("login"));
//login.click();
//driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
//WebElement loc = driver.findElement(By.name("location"));
//Select s=new Select(loc);
//s.selectByVisibleText("London");
//WebElement hotel = driver.findElement(By.id("hotels"));
//Select s1=new Select(hotel);
//s1.selectByVisibleText("Hotel Sunshine");
//WebElement room = driver.findElement(By.id("room_type"));
//Select s2=new Select(room);
//s2.selectByVisibleText("Deluxe");
//WebElement nos = driver.findElement(By.id("room_nos"));
//Select s3=new Select(nos);
//s3.selectByVisibleText("1 - One");
//WebElement in = driver.findElement(By.name("datepick_in"));
//in.sendKeys("3/30/2022");
//WebElement out=driver.findElement(By.name("datepick_out"));
//out.sendKeys("4/2/2022");
//WebElement adult = driver.findElement(By.id("adult_room"));
//Select s4=new Select(adult);
//s4.selectByVisibleText("2 - Two");
//WebElement child = driver.findElement(By.id("child_room"));
//Select s5=new Select(child);
//s5.selectByIndex(1);
//WebElement search = driver.findElement(By.id("Submit"));
//search.click();
//driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
//WebElement radio = driver.findElement(By.id("radiobutton_0"));
//radio.click();
//WebElement cont = driver.findElement(By.id("continue"));
//cont.click();
//WebElement name = driver.findElement(By.id("first_name"));
//name.sendKeys("priya");
//WebElement last_n = driver.findElement(By.id("last_name"));
//last_n.sendKeys("venkat");
//WebElement addr = driver.findElement(By.id("address"));
//addr.sendKeys("34,tyti,chenai");
//WebElement card = driver.findElement(By.id("cc_num"));
//card.sendKeys("2345678923456789");
//WebElement card_type = driver.findElement(By.id("cc_type"));
//Select s6=new Select(card_type);
//s6.selectByVisibleText("VISA");
//WebElement month = driver.findElement(By.id("cc_exp_month"));
//Select s7=new Select(month);
//s7.selectByVisibleText("February");
//WebElement year = driver.findElement(By.id("cc_exp_year"));
//Select s8=new Select(year);
//s8.selectByVisibleText("2022");
//WebElement cvv = driver.findElement(By.id("cc_cvv"));
//cvv.sendKeys("345");
//WebElement book = driver.findElement(By.id("book_now"));
//book.click();
//driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
//WebElement logout = driver.findElement(By.id("logout"));
//logout.click();
//TakesScreenshot ts=(TakesScreenshot)driver;
//File src=ts.getScreenshotAs(OutputType.FILE);
//File dest=new File("C:\\Users\\DELL\\eclipse-workspace\\Selenium\\screenshot\\logout.png");
//FileUtils.copyFile(src, dest);
driver.get("http://automationpractice.com/index.php");
WebElement women = driver.findElement(By.linkText("Women"));
women.click();
Thread.sleep(3000);
WebElement dress = driver.findElement(By.xpath("(//img[@class='replace-2x img-responsive'])[5]"));
dress.click();
WebElement cart = driver.findElement(By.id("add_to_cart"));
cart.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement check = driver.findElement(By.cssSelector("a[title='Proceed to checkout']"));
check.click();
WebElement check1 = driver.findElement(By.xpath("(//a[@title='Proceed to checkout'])[2]"));
check1.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement create = driver.findElement(By.id("email_create"));
create.sendKeys("prajen59@gmail.com");
WebElement submit = driver.findElement(By.id("SubmitCreate"));
submit.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement gen=driver.findElement(By.id("uniform-id_gender2"));
gen.click();
WebElement fname = driver.findElement(By.id("customer_firstname"));
fname.sendKeys("priya");
WebElement lname = driver.findElement(By.id("customer_lastname"));
lname.sendKeys("venkat");
WebElement pwd = driver.findElement(By.id("passwd"));
pwd.sendKeys("Prajen1@09");
WebElement day = driver.findElement(By.id("days"));
Select s=new Select(day);
s.selectByValue("24");
WebElement mon = driver.findElement(By.id("months"));
Select s1=new Select(mon);
s1.selectByValue("2");
WebElement year = driver.findElement(By.id("years"));
Select s2=new Select(year);
s2.selectByValue("1992");
WebElement f_name = driver.findElement(By.name("firstname"));
f_name.sendKeys("priya");
WebElement l_name = driver.findElement(By.name("lastname"));
l_name.sendKeys("venkat");
WebElement addr = driver.findElement(By.id("address1"));
addr.sendKeys("24,snjsdnjks,gjjs");
WebElement city = driver.findElement(By.id("city"));
city.sendKeys("chenai");
WebElement stat = driver.findElement(By.id("id_state"));
Select s3=new Select(stat);
s3.selectByVisibleText("Alaska");
WebElement post = driver.findElement(By.id("postcode"));
post.sendKeys("00000");
WebElement no = driver.findElement(By.id("phone_mobile"));
no.sendKeys("856246");
WebElement alis = driver.findElement(By.id("alias"));
alis.sendKeys("24,snjsdnjks,gjjs");
WebElement reg = driver.findElement(By.id("submitAccount"));
reg.click();
driver.manage().timeouts().implicitlyWait(40,TimeUnit.SECONDS);
WebElement proceed = driver.findElement(By.name("processAddress"));
proceed.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
//driver.switchTo().alert().dismiss();

driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement tick = driver.findElement(By.id("cgv"));
tick.click();

WebElement carr = driver.findElement(By.name("processCarrier"));
carr.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement pay = driver.findElement(By.className("bankwire"));
pay.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
WebElement proceed1 = driver.findElement(By.cssSelector("[class='button btn btn-default button-medium']"));
proceed1.click();
driver.manage().timeouts().implicitlyWait(30,TimeUnit.SECONDS);
TakesScreenshot ts=(TakesScreenshot)driver;
File src=ts.getScreenshotAs(OutputType.FILE);
File dest=new File("C:\\Users\\DELL\\eclipse-workspace\\Selenium\\screenshot\\payment.png");
FileUtils.copyFile(src, dest);

	}
}
